# -*- coding: utf-8 -*-
"""DFD_Table-Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z22FRAO2jN0OhUYF-UFGwjuXQclniLha
"""

import pandas as pd

# TODOs
## Associate SB to Address Collections
## Group BSMT with address within PL boundary

import tkinter
from tkinter.filedialog import askdirectory, askopenfilename

## Attempt to put the file dialog window in front... https://stackoverflow.com/questions/3375227/how-to-give-tkinter-file-dialog-focus
# root = tkinter.Tk()
# root.withdraw()
# root.lift()
# root.focus_force()
ppc_path = askopenfilename(title="Select Fibre Data excel file:")
xl = pd.ExcelFile(ppc_path)

for i, sheet in enumerate(xl.sheet_names):
    print(i, ":", sheet)
# print(xl.sheet_names)  # see all sheet names
sheet_name = int(input("Select sheet with PPC data:"))
sheet_name = xl.sheet_names[sheet_name]
df = xl.parse(sheet_name, header=2)  # read a specific sheet to DataFrame

df["Splice Number"] = df["Splice Number"].replace("FDH", 0)
df["Parent Number"] = df["Parent Number"].replace("FDH", 0)
df = df.set_index('Splice Number')
df.head()

"""# Upload all the tables generated from Grasshopper (address_text.gh)"""

!mkdir Tables

!mv *.csv Tables
# !rm -rf horizontal/
# df0 = df0.transpose() # Fixed in Grasshopper
from os import listdir
path=askdirectory(title="Select AutoCAD Table Export CSV Folder", parent=root)
csv_list = listdir(path)

"""# Add all the tables to a dictionary"""

# df0 = pd.read_csv("0.csv")

d = {}
for x in range(0, len(csv_list)):
  csv_file = prepend + csv_list[x]
  data = pd.read_csv(csv_file, header=None)
  d["{0}".format(data.at[0, 0])] = data

# Generate a series of addresses from
# INPUTS
# 1. A count (total addresses)
# 2. (Optional) Indices of any basements
# 3. An offset (i.e. +3)
# 4. A start address
# 5. Streetname
# OUTPUTS
#     A range of addresses

fcp = 21622
struc = "SB-2061A3-28"
count = 9
bsmt = []
offset = 4
address1 = 903
street = " CANAVERAL CR SW"
addresses = [str(address1) + street]

for i in range(1, count):
  if i == 1:
    addr = address1

  new_addr = addr + offset
  addresses.append(str(new_addr) + street)
  addr = new_addr

# Generate the series of drops
# INPUTS
# 1. A count
# 2. (Optional) Indices of any basements
# 3. Starting fibre number (i.e. 432)

fibre_start = 301
fibre_end = 324
fibres = [fibre_start]

for i in range(1, count):
  #if i in bsmt:
    # f = 
  fibres.append(fibre_start + i)

fcp = 21622
struc = "SB-2061A3-28"
title = "FCP#" + str(fcp) + " HARD-SPLICE DROPS IN SPLICE TRAYS AT " + str(struc)
title

df = pd.DataFrame(list(zip(addresses, fibres)),
               columns =['Address', 'Fibre'])

df.to_csv(str(fcp) + ".csv", header=title, index=None)

df.to_excel(str(fcp) + ".xlsx", header=None, index=None, merge_cells=True, sheet_name=str(fcp))