ppc_columns = ['AFL ID', 'EnceptaID', 'Parent Encepta ID', 'LPDS_ID', 'Address D',
               'Building ID', 'Central Office', 'FMS_ID', 'Unit No', 'Street No',
               'Street No Suffix', 'Directional Prefix', 'StreetName', 'Street Type',
               'Directional Suffix', 'City Name', 'Latitude', 'Longitude', 'COID',
               'FSA', 'Premise Type PPC', 'Premise Type AFL', 'DoorAccessMDU',
               'HousingType', 'FirstNations', 'Storeys', 'BusCount', 'ResCount',
               'VacLot', 'DoesNotExist', 'BusinessName', 'BusinessIndustry', 'NAIC',
               'AdditionalNotes', 'ParentAddressforMXUGrouping', 'Distribution',
               'Terminal ID for Copper', 'Drop', 'Entrance Cable or Individual Drops',
               'Common Demarc Identifier', 'GPON', 'BusCountDesign', 'ResCountDesign',
               'TerminalID', 'DropDesign', 'DistributionDesign', 'TerminalLocation',
               'FiberAllocation', 'DedicatedFiber', 'NetworkPlaced', 'Notes',
               'SheetNo', 'FSATransfer', 'PremiseUpdateType', 'FiberOverrideAmount',
               'FiberCount', 'Drop (aerial, conduit, aerial+conduit, Lateral)',
               'Distribution  (aerial, conduit or direct buried)']
